### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by RustyToms** [KeithConroy/fireeye#1]
The twitter project is looking good! But I'd like to see a little more of what you can do:
- [x] split out the tweets as their own model
- [x] render more things using components, such as each individual tweet and the user info box on the top left
- [x] Add a class name to the elements, and then use the class name as the CSS selector instead of using nested elements
- [x] Try to make the app as close to the picture we provided as possible
- [x] Add tests
- [x] make regular commits to github as you work
- [x] remove Bootstrap from the project

**Comment by KeithConroy** [comment]
Requested changes have been completed.

I had asked Jessica for a higher resolution of the image provided with the challenge, but have not received one.  I did the best I could to match the low resolution image, but could not make out the finer details.

I will email Jessica to let her know I am done with the changes.
